export const routines = [
  {
    standard: 1,
    periods: [
      {
        day: "Mon",
        number: 1,
        subject: "Political Science",
        teacher: "Anusuya Deshpande",
      },
      {
        day: "Mon",
        number: 2,
        subject: "Business Studies",
        teacher: "Chandrakala Agarwal",
      },
      {
        day: "Mon",
        number: 3,
        subject: "Media Studies",
        teacher: "Amaresh Patil",
      },
      {
        day: "Mon",
        number: 4,
        subject: "Political Science",
        teacher: "Bhuvanesh Abbott",
      },
      {
        day: "Mon",
        number: 5,
        subject: "Geography",
        teacher: "Asha Bandopadhyay",
      },
      {
        day: "Mon",
        number: 6,
        subject: "Geography",
        teacher: "Chandrani Reddy",
      },
      {
        day: "Mon",
        number: 7,
        subject: "Design and Technology",
        teacher: "Girika Iyer",
      },
      {
        day: "Mon",
        number: 8,
        subject: "Health Education",
        teacher: "Suresh Bharadwaj",
      },
      {
        day: "Tue",
        number: 1,
        subject: "Civics",
        teacher: "Preity Somayaji",
      },
      {
        day: "Tue",
        number: 2,
        subject: "Environmental Science",
        teacher: "Baala Nambeesan",
      },
      {
        day: "Tue",
        number: 3,
        subject: "English",
        teacher: "Birjesh Embranthiri Jr.",
      },
      {
        day: "Tue",
        number: 4,
        subject: "Entrepreneurship",
        teacher: "Devi Verma IV",
      },
      {
        day: "Tue",
        number: 5,
        subject: "Religious Studies",
        teacher: "Kamala Varma",
      },
      {
        day: "Tue",
        number: 6,
        subject: "Political Science",
        teacher: "Shantanu Suthar",
      },
      {
        day: "Tue",
        number: 7,
        subject: "Dance",
        teacher: "Bhooshit Saini",
      },
      {
        day: "Tue",
        number: 8,
        subject: "Civics",
        teacher: "Nirbhay Khan",
      },
      {
        day: "Wed",
        number: 1,
        subject: "Home Economics",
        teacher: "Bilva Varrier",
      },
      {
        day: "Wed",
        number: 2,
        subject: "Design and Technology",
        teacher: "Ananta Nair",
      },
      {
        day: "Wed",
        number: 3,
        subject: "Art",
        teacher: "Shreyashi Khatri",
      },
      {
        day: "Wed",
        number: 4,
        subject: "Philosophy",
        teacher: "Sharda Butt",
      },
      {
        day: "Wed",
        number: 5,
        subject: "Home Economics",
        teacher: "Girja Nambeesan",
      },
      {
        day: "Wed",
        number: 6,
        subject: "Business Studies",
        teacher: "Bhaaswar Tandon",
      },
      {
        day: "Wed",
        number: 7,
        subject: "Entrepreneurship",
        teacher: "Ms. Dhanalakshmi Talwar",
      },
      {
        day: "Wed",
        number: 8,
        subject: "Drama",
        teacher: "Shrishti Tagore DDS",
      },
      {
        day: "Thu",
        number: 1,
        subject: "Design and Technology",
        teacher: "Aslesha Mehrotra",
      },
      {
        day: "Thu",
        number: 2,
        subject: "Entrepreneurship",
        teacher: "Bandhul Ahluwalia",
      },
      {
        day: "Thu",
        number: 3,
        subject: "Economics",
        teacher: "Gatik Varman IV",
      },
      {
        day: "Thu",
        number: 4,
        subject: "Chemistry",
        teacher: "Vrinda Singh",
      },
      {
        day: "Thu",
        number: 5,
        subject: "History",
        teacher: "Abhirath Kaur III",
      },
      {
        day: "Thu",
        number: 6,
        subject: "Ethics",
        teacher: "Chandrakin Guha",
      },
      {
        day: "Thu",
        number: 7,
        subject: "Art",
        teacher: "Gotum Jangid",
      },
      {
        day: "Thu",
        number: 8,
        subject: "Ethics",
        teacher: "Vasudha Kapoor",
      },
      {
        day: "Fri",
        number: 1,
        subject: "Design and Technology",
        teacher: "Eekalabya Joshi",
      },
      {
        day: "Fri",
        number: 2,
        subject: "Information Technology",
        teacher: "Rajiv Talwar",
      },
      {
        day: "Fri",
        number: 3,
        subject: "Entrepreneurship",
        teacher: "Harinakshi Kakkar",
      },
      {
        day: "Fri",
        number: 4,
        subject: "History",
        teacher: "Avantika Joshi",
      },
      {
        day: "Fri",
        number: 5,
        subject: "Media Studies",
        teacher: "Vaijayanti Pothuvaal IV",
      },
      {
        day: "Fri",
        number: 6,
        subject: "Sociology",
        teacher: "Baalagopaal Nehru",
      },
      {
        day: "Fri",
        number: 7,
        subject: "History",
        teacher: "Mr. Dandapaani Bharadwaj V",
      },
      {
        day: "Fri",
        number: 8,
        subject: "Computer Science",
        teacher: "Lila Chaturvedi",
      },
      {
        day: "Sat",
        number: 1,
        subject: "Home Economics",
        teacher: "Shakti Dubashi I",
      },
      {
        day: "Sat",
        number: 2,
        subject: "Agriculture",
        teacher: "Dhaanyalakshmi Agarwal",
      },
      {
        day: "Sat",
        number: 3,
        subject: "Physical Education",
        teacher: "Ameyatma Mahajan",
      },
      {
        day: "Sat",
        number: 4,
        subject: "Foreign Language",
        teacher: "Bhagwati Kaur",
      },
      {
        day: "Sat",
        number: 5,
        subject: "Environmental Science",
        teacher: "Daiwik Patil",
      },
      {
        day: "Sat",
        number: 6,
        subject: "Accounting",
        teacher: "Chandradev Dwivedi",
      },
      {
        day: "Sat",
        number: 7,
        subject: "Economics",
        teacher: "Apsara Pillai",
      },
      {
        day: "Sat",
        number: 8,
        subject: "Design and Technology",
        teacher: "Anandamayi Naik",
      },
    ],
  },
  {
    standard: 2,
    periods: [
      {
        day: "Mon",
        number: 1,
        subject: "Political Science",
        teacher: "Mohana Jha",
      },
      {
        day: "Mon",
        number: 2,
        subject: "Home Economics",
        teacher: "Bhudev Tagore",
      },
      {
        day: "Mon",
        number: 3,
        subject: "Political Science",
        teacher: "Atreyee Kaniyar",
      },
      {
        day: "Mon",
        number: 4,
        subject: "Physical Education",
        teacher: "Aasa Tandon",
      },
      {
        day: "Mon",
        number: 5,
        subject: "Health Education",
        teacher: "Suman Butt",
      },
      {
        day: "Mon",
        number: 6,
        subject: "Business Studies",
        teacher: "Shashikala Prajapat",
      },
      {
        day: "Mon",
        number: 7,
        subject: "Computer Science",
        teacher: "Dr. Hari Bhat",
      },
      {
        day: "Mon",
        number: 8,
        subject: "Chemistry",
        teacher: "Manisha Chattopadhyay",
      },
      {
        day: "Tue",
        number: 1,
        subject: "English",
        teacher: "Gopee Patel",
      },
      {
        day: "Tue",
        number: 2,
        subject: "Entrepreneurship",
        teacher: "Paramartha Trivedi",
      },
      { day: "Tue", number: 3, subject: "Art", teacher: "Javas Bhat" },
      {
        day: "Tue",
        number: 4,
        subject: "English",
        teacher: "Avadhesh Ahuja",
      },
      {
        day: "Tue",
        number: 5,
        subject: "Ethics",
        teacher: "Gudakesa Bharadwaj",
      },
      {
        day: "Tue",
        number: 6,
        subject: "Information Technology",
        teacher: "Ahilya Ahuja",
      },
      {
        day: "Tue",
        number: 7,
        subject: "Ethics",
        teacher: "Jyoti Chopra",
      },
      {
        day: "Tue",
        number: 8,
        subject: "History",
        teacher: "Mayoor Dwivedi",
      },
      {
        day: "Wed",
        number: 1,
        subject: "Library Science",
        teacher: "Daevika Malik",
      },
      {
        day: "Wed",
        number: 2,
        subject: "Religious Studies",
        teacher: "Vasudeva Desai",
      },
      {
        day: "Wed",
        number: 3,
        subject: "Astronomy",
        teacher: "Bhadra Abbott",
      },
      {
        day: "Wed",
        number: 4,
        subject: "English",
        teacher: "Dhana Patel",
      },
      {
        day: "Wed",
        number: 5,
        subject: "Ethics",
        teacher: "Girish Gupta",
      },
      {
        day: "Wed",
        number: 6,
        subject: "Political Science",
        teacher: "Girija Joshi",
      },
      {
        day: "Wed",
        number: 7,
        subject: "Library Science",
        teacher: "Dr. Atreyee Pillai",
      },
      {
        day: "Wed",
        number: 8,
        subject: "Sociology",
        teacher: "Param Shah",
      },
      {
        day: "Thu",
        number: 1,
        subject: "Psychology",
        teacher: "Apsara Bharadwaj",
      },
      {
        day: "Thu",
        number: 2,
        subject: "Science",
        teacher: "Adhiraj Ahluwalia",
      },
      {
        day: "Thu",
        number: 3,
        subject: "Media Studies",
        teacher: "Arun Gupta",
      },
      {
        day: "Thu",
        number: 4,
        subject: "Mathematics",
        teacher: "Dr. Lalita Rana",
      },
      {
        day: "Thu",
        number: 5,
        subject: "Science",
        teacher: "Avantika Dwivedi",
      },
      {
        day: "Thu",
        number: 6,
        subject: "Design and Technology",
        teacher: "Abani Mukhopadhyay",
      },
      {
        day: "Thu",
        number: 7,
        subject: "English",
        teacher: "Chandrabhaga Adiga",
      },
      {
        day: "Thu",
        number: 8,
        subject: "English",
        teacher: "Aishani Joshi",
      },
      {
        day: "Fri",
        number: 1,
        subject: "Computer Science",
        teacher: "Avantika Iyer-Prajapat PhD",
      },
      {
        day: "Fri",
        number: 2,
        subject: "Health Education",
        teacher: "Anaadi Verma",
      },
      {
        day: "Fri",
        number: 3,
        subject: "Art",
        teacher: "Aaratrika Namboothiri",
      },
      {
        day: "Fri",
        number: 4,
        subject: "Philosophy",
        teacher: "Gopi Iyer",
      },
      {
        day: "Fri",
        number: 5,
        subject: "Drama",
        teacher: "Triloki Nath Talwar",
      },
      {
        day: "Fri",
        number: 6,
        subject: "Philosophy",
        teacher: "Anila Sethi-Asan",
      },
      {
        day: "Fri",
        number: 7,
        subject: "Science",
        teacher: "Chandak Sinha",
      },
      {
        day: "Fri",
        number: 8,
        subject: "Religious Studies",
        teacher: "Annapurna Sinha",
      },
      {
        day: "Sat",
        number: 1,
        subject: "Computer Science",
        teacher: "Akshayakeerti Saini",
      },
      {
        day: "Sat",
        number: 2,
        subject: "Drama",
        teacher: "Siddhran Banerjee",
      },
      {
        day: "Sat",
        number: 3,
        subject: "Environmental Science",
        teacher: "Sumitra Bhat",
      },
      {
        day: "Sat",
        number: 4,
        subject: "Physical Education",
        teacher: "Somnath Jha",
      },
      {
        day: "Sat",
        number: 5,
        subject: "Agriculture",
        teacher: "Priya Dwivedi",
      },
      {
        day: "Sat",
        number: 6,
        subject: "Ethics",
        teacher: "Harita Chopra",
      },
      {
        day: "Sat",
        number: 7,
        subject: "Religious Studies",
        teacher: "Preity Kaul",
      },
      {
        day: "Sat",
        number: 8,
        subject: "Dance",
        teacher: "Keerti Jangid",
      },
    ],
  },
  {
    standard: 3,
    periods: [
      {
        day: "Mon",
        number: 1,
        subject: "Science",
        teacher: "Sheela Mishra",
      },
      {
        day: "Mon",
        number: 2,
        subject: "Art",
        teacher: "Chitraksh Nehru",
      },
      {
        day: "Mon",
        number: 3,
        subject: "Physics",
        teacher: "Chidaakaash Pilla",
      },
      {
        day: "Mon",
        number: 4,
        subject: "Art",
        teacher: "Jaimini Abbott",
      },
      {
        day: "Mon",
        number: 5,
        subject: "Biology",
        teacher: "Chinmayanand Patel",
      },
      {
        day: "Mon",
        number: 6,
        subject: "Biology",
        teacher: "Divakar Guha",
      },
      {
        day: "Mon",
        number: 7,
        subject: "Accounting",
        teacher: "Diksha Reddy",
      },
      {
        day: "Mon",
        number: 8,
        subject: "Physical Science",
        teacher: "Meena Dutta",
      },
      {
        day: "Tue",
        number: 1,
        subject: "Political Science",
        teacher: "Udai Kaul",
      },
      {
        day: "Tue",
        number: 2,
        subject: "Biology",
        teacher: "Ayushmati Desai",
      },
      { day: "Tue", number: 3, subject: "Art", teacher: "Ritesh Kaul" },
      {
        day: "Tue",
        number: 4,
        subject: "Social Studies",
        teacher: "Mangalya Gandhi-Devar",
      },
      {
        day: "Tue",
        number: 5,
        subject: "Environmental Science",
        teacher: "Ms. Amodini Iyer",
      },
      {
        day: "Tue",
        number: 6,
        subject: "Social Studies",
        teacher: "Sher Ahuja",
      },
      {
        day: "Tue",
        number: 7,
        subject: "Art",
        teacher: "Giriraaj Suthar",
      },
      {
        day: "Tue",
        number: 8,
        subject: "English",
        teacher: "Meenakshi Pandey",
      },
      {
        day: "Wed",
        number: 1,
        subject: "English",
        teacher: "Mr. Deeptimay Ahluwalia",
      },
      {
        day: "Wed",
        number: 2,
        subject: "Sociology",
        teacher: "Mr. Triloki Nath Chaturvedi-Bhat",
      },
      {
        day: "Wed",
        number: 3,
        subject: "Drama",
        teacher: "Kanishka Adiga",
      },
      {
        day: "Wed",
        number: 4,
        subject: "Sociology",
        teacher: "Aadrika Namboothiri",
      },
      {
        day: "Wed",
        number: 5,
        subject: "Psychology",
        teacher: "Sharmila Bhattathiri",
      },
      {
        day: "Wed",
        number: 6,
        subject: "History",
        teacher: "Trilokanath Bharadwaj",
      },
      {
        day: "Wed",
        number: 7,
        subject: "Psychology",
        teacher: "Harinakshi Dubashi",
      },
      {
        day: "Wed",
        number: 8,
        subject: "Philosophy",
        teacher: "Kashyapi Sharma",
      },
      {
        day: "Thu",
        number: 1,
        subject: "Health Education",
        teacher: "Hari Naik",
      },
      {
        day: "Thu",
        number: 2,
        subject: "Business Studies",
        teacher: "Chandak Khatri",
      },
      {
        day: "Thu",
        number: 3,
        subject: "Environmental Science",
        teacher: "Miss Soma Gupta IV",
      },
      {
        day: "Thu",
        number: 4,
        subject: "Agriculture",
        teacher: "Bhanumati Malik",
      },
      {
        day: "Thu",
        number: 5,
        subject: "Psychology",
        teacher: "Chetanaanand Gowda",
      },
      {
        day: "Thu",
        number: 6,
        subject: "Physics",
        teacher: "Bahula Nair",
      },
      {
        day: "Thu",
        number: 7,
        subject: "Home Economics",
        teacher: "Jaimini Iyer",
      },
      {
        day: "Thu",
        number: 8,
        subject: "Health Education",
        teacher: "Anal Reddy",
      },
      {
        day: "Fri",
        number: 1,
        subject: "Science",
        teacher: "Dr. Akshata Agarwal",
      },
      {
        day: "Fri",
        number: 2,
        subject: "Agriculture",
        teacher: "Devika Tandon",
      },
      {
        day: "Fri",
        number: 3,
        subject: "Environmental Science",
        teacher: "Aatreya Nehru",
      },
      {
        day: "Fri",
        number: 4,
        subject: "Geography",
        teacher: "Balachandra Menon",
      },
      {
        day: "Fri",
        number: 5,
        subject: "Biology",
        teacher: "Jaya Pothuvaal IV",
      },
      {
        day: "Fri",
        number: 6,
        subject: "History",
        teacher: "Bhadra Ahuja",
      },
      {
        day: "Fri",
        number: 7,
        subject: "Civics",
        teacher: "Dr. Niranjan Banerjee",
      },
      {
        day: "Fri",
        number: 8,
        subject: "English",
        teacher: "Aadidev Varrier",
      },
      {
        day: "Sat",
        number: 1,
        subject: "Psychology",
        teacher: "Bandhul Achari",
      },
      {
        day: "Sat",
        number: 2,
        subject: "Drama",
        teacher: "Niranjan Iyer",
      },
      {
        day: "Sat",
        number: 3,
        subject: "Drama",
        teacher: "Aanjaneya Reddy-Tandon",
      },
      {
        day: "Sat",
        number: 4,
        subject: "Business Studies",
        teacher: "Gayatri Khanna",
      },
      {
        day: "Sat",
        number: 5,
        subject: "Design and Technology",
        teacher: "Vidya Chopra",
      },
      {
        day: "Sat",
        number: 6,
        subject: "Information Technology",
        teacher: "Chakravarti Suthar",
      },
      {
        day: "Sat",
        number: 7,
        subject: "Social Studies",
        teacher: "Chandra Kapoor",
      },
      {
        day: "Sat",
        number: 8,
        subject: "Home Economics",
        teacher: "Jai Dubashi",
      },
    ],
  },
  {
    standard: 4,
    periods: [
      {
        day: "Mon",
        number: 1,
        subject: "Entrepreneurship",
        teacher: "Shobhana Bhadresha III",
      },
      {
        day: "Mon",
        number: 2,
        subject: "Accounting",
        teacher: "Mr. Arjun Malik",
      },
      {
        day: "Mon",
        number: 3,
        subject: "Philosophy",
        teacher: "Karthik Chattopadhyay",
      },
      {
        day: "Mon",
        number: 4,
        subject: "English",
        teacher: "Mukesh Adiga",
      },
      {
        day: "Mon",
        number: 5,
        subject: "Political Science",
        teacher: "Darshwana Patil",
      },
      {
        day: "Mon",
        number: 6,
        subject: "Philosophy",
        teacher: "Hiranmay Namboothiri",
      },
      {
        day: "Mon",
        number: 7,
        subject: "Media Studies",
        teacher: "Ujjwal Ahluwalia",
      },
      {
        day: "Mon",
        number: 8,
        subject: "Library Science",
        teacher: "Vinay Mehra",
      },
      {
        day: "Tue",
        number: 1,
        subject: "Foreign Language",
        teacher: "Udai Suthar",
      },
      {
        day: "Tue",
        number: 2,
        subject: "Music",
        teacher: "Aanjaneya Pandey",
      },
      {
        day: "Tue",
        number: 3,
        subject: "Business Studies",
        teacher: "Brijesh Desai",
      },
      {
        day: "Tue",
        number: 4,
        subject: "Ethics",
        teacher: "Kin Marar",
      },
      {
        day: "Tue",
        number: 5,
        subject: "Art",
        teacher: "Shivakari Ahuja",
      },
      {
        day: "Tue",
        number: 6,
        subject: "Sociology",
        teacher: "Sushil Varman",
      },
      {
        day: "Tue",
        number: 7,
        subject: "Psychology",
        teacher: "Mrs. Atreyi Panicker IV",
      },
      {
        day: "Tue",
        number: 8,
        subject: "Psychology",
        teacher: "Vedanga Ahuja",
      },
      {
        day: "Wed",
        number: 1,
        subject: "Sociology",
        teacher: "Dr. Dayaanidhi Mishra",
      },
      {
        day: "Wed",
        number: 2,
        subject: "Biology",
        teacher: "Poornima Khan Sr.",
      },
      {
        day: "Wed",
        number: 3,
        subject: "Astronomy",
        teacher: "Balagopal Banerjee",
      },
      {
        day: "Wed",
        number: 4,
        subject: "Physics",
        teacher: "Miss Pramila Reddy",
      },
      {
        day: "Wed",
        number: 5,
        subject: "Environmental Science",
        teacher: "Ravi Johar",
      },
      {
        day: "Wed",
        number: 6,
        subject: "Sociology",
        teacher: "Aadinath Sinha",
      },
      {
        day: "Wed",
        number: 7,
        subject: "Political Science",
        teacher: "Harit Kocchar",
      },
      {
        day: "Wed",
        number: 8,
        subject: "Dance",
        teacher: "Chandrani Pandey-Ahluwalia IV",
      },
      {
        day: "Thu",
        number: 1,
        subject: "Philosophy",
        teacher: "Chatur Bandopadhyay",
      },
      {
        day: "Thu",
        number: 2,
        subject: "Economics",
        teacher: "Bhuvaneshwar Malik",
      },
      {
        day: "Thu",
        number: 3,
        subject: "Physics",
        teacher: "Archan Khatri",
      },
      {
        day: "Thu",
        number: 4,
        subject: "Dance",
        teacher: "Rita Dhawan",
      },
      {
        day: "Thu",
        number: 5,
        subject: "Dance",
        teacher: "Uttam Arora",
      },
      {
        day: "Thu",
        number: 6,
        subject: "Computer Science",
        teacher: "Prathamesh Prajapat",
      },
      {
        day: "Thu",
        number: 7,
        subject: "Art",
        teacher: "Jyotis Saini",
      },
      {
        day: "Thu",
        number: 8,
        subject: "Home Economics",
        teacher: "Tanushree Marar",
      },
      {
        day: "Fri",
        number: 1,
        subject: "Psychology",
        teacher: "Vasudeva Tandon",
      },
      {
        day: "Fri",
        number: 2,
        subject: "History",
        teacher: "Marut Sethi",
      },
      {
        day: "Fri",
        number: 3,
        subject: "History",
        teacher: "Manikya Embranthiri",
      },
      {
        day: "Fri",
        number: 4,
        subject: "Drama",
        teacher: "Veda Pilla MD",
      },
      {
        day: "Fri",
        number: 5,
        subject: "Library Science",
        teacher: "Diksha Prajapat",
      },
      {
        day: "Fri",
        number: 6,
        subject: "Mathematics",
        teacher: "Ekaparnika Abbott",
      },
      {
        day: "Fri",
        number: 7,
        subject: "Mathematics",
        teacher: "Malti Nambeesan",
      },
      {
        day: "Fri",
        number: 8,
        subject: "Geography",
        teacher: "Shivakari Agarwal",
      },
      {
        day: "Sat",
        number: 1,
        subject: "Entrepreneurship",
        teacher: "Vasudeva Agarwal",
      },
      {
        day: "Sat",
        number: 2,
        subject: "Sociology",
        teacher: "Brahmdev Dutta",
      },
      {
        day: "Sat",
        number: 3,
        subject: "Civics",
        teacher: "Sunita Ahuja",
      },
      {
        day: "Sat",
        number: 4,
        subject: "Political Science",
        teacher: "Narinder Bhat",
      },
      {
        day: "Sat",
        number: 5,
        subject: "Physics",
        teacher: "Gautami Ganaka",
      },
      {
        day: "Sat",
        number: 6,
        subject: "Religious Studies",
        teacher: "Gatik Khatri",
      },
      {
        day: "Sat",
        number: 7,
        subject: "Physics",
        teacher: "Chandrabhaga Varrier",
      },
      {
        day: "Sat",
        number: 8,
        subject: "Sociology",
        teacher: "Ms. Preity Mukhopadhyay I",
      },
    ],
  },
  {
    standard: 5,
    periods: [
      {
        day: "Mon",
        number: 1,
        subject: "Physics",
        teacher: "Aanandaswarup Namboothiri V",
      },
      {
        day: "Mon",
        number: 2,
        subject: "Environmental Science",
        teacher: "Pushti Kakkar",
      },
      {
        day: "Mon",
        number: 3,
        subject: "Religious Studies",
        teacher: "Parvati Kocchar",
      },
      {
        day: "Mon",
        number: 4,
        subject: "Economics",
        teacher: "Miss Vidya Guneta",
      },
      {
        day: "Mon",
        number: 5,
        subject: "Physical Science",
        teacher: "Chakradhar Achari",
      },
      {
        day: "Mon",
        number: 6,
        subject: "Civics",
        teacher: "Bela Varrier",
      },
      {
        day: "Mon",
        number: 7,
        subject: "Information Technology",
        teacher: "Aanandinii Guneta MD",
      },
      {
        day: "Mon",
        number: 8,
        subject: "History",
        teacher: "Kashyapi Guneta",
      },
      {
        day: "Tue",
        number: 1,
        subject: "Library Science",
        teacher: "Dr. Baalagopaal Pothuvaal",
      },
      {
        day: "Tue",
        number: 2,
        subject: "Psychology",
        teacher: "Laal Mehrotra",
      },
      {
        day: "Tue",
        number: 3,
        subject: "Biology",
        teacher: "Shiv Rana",
      },
      {
        day: "Tue",
        number: 4,
        subject: "Religious Studies",
        teacher: "Girik Namboothiri",
      },
      {
        day: "Tue",
        number: 5,
        subject: "Home Economics",
        teacher: "Gauraang Ahluwalia",
      },
      {
        day: "Tue",
        number: 6,
        subject: "History",
        teacher: "Opaline Malik",
      },
      {
        day: "Tue",
        number: 7,
        subject: "Civics",
        teacher: "Devadatt Banerjee IV",
      },
      {
        day: "Tue",
        number: 8,
        subject: "Accounting",
        teacher: "Aditya Gandhi",
      },
      {
        day: "Wed",
        number: 1,
        subject: "Media Studies",
        teacher: "Gaurang Pilla",
      },
      {
        day: "Wed",
        number: 2,
        subject: "Dance",
        teacher: "Hiranmaya Kaniyar",
      },
      {
        day: "Wed",
        number: 3,
        subject: "Religious Studies",
        teacher: "Devani Talwar",
      },
      {
        day: "Wed",
        number: 4,
        subject: "Agriculture",
        teacher: "Udit Khatri",
      },
      {
        day: "Wed",
        number: 5,
        subject: "Psychology",
        teacher: "Eshita Kapoor",
      },
      {
        day: "Wed",
        number: 6,
        subject: "Geography",
        teacher: "Lalita Jha",
      },
      {
        day: "Wed",
        number: 7,
        subject: "Economics",
        teacher: "Saroja Verma",
      },
      {
        day: "Wed",
        number: 8,
        subject: "English",
        teacher: "Kali Khanna",
      },
      {
        day: "Thu",
        number: 1,
        subject: "Science",
        teacher: "Nikita Kapoor",
      },
      {
        day: "Thu",
        number: 2,
        subject: "Physical Education",
        teacher: "Miss Aruna Kakkar",
      },
      {
        day: "Thu",
        number: 3,
        subject: "Political Science",
        teacher: "Bhagwanti Dutta",
      },
      {
        day: "Thu",
        number: 4,
        subject: "Psychology",
        teacher: "Bankimchandra Kocchar",
      },
      {
        day: "Thu",
        number: 5,
        subject: "Library Science",
        teacher: "Chandani Desai",
      },
      {
        day: "Thu",
        number: 6,
        subject: "Design and Technology",
        teacher: "Bheeshma Pilla V",
      },
      {
        day: "Thu",
        number: 7,
        subject: "Physical Science",
        teacher: "Miss Eshita Tandon",
      },
      {
        day: "Thu",
        number: 8,
        subject: "Environmental Science",
        teacher: "Daevika Rana",
      },
      {
        day: "Fri",
        number: 1,
        subject: "Psychology",
        teacher: "Ghanshyam Khan",
      },
      {
        day: "Fri",
        number: 2,
        subject: "Ethics",
        teacher: "Chandira Khanna",
      },
      {
        day: "Fri",
        number: 3,
        subject: "Science",
        teacher: "Shubha Dhawan",
      },
      {
        day: "Fri",
        number: 4,
        subject: "Home Economics",
        teacher: "Mrs. Tanirika Banerjee",
      },
      {
        day: "Fri",
        number: 5,
        subject: "Business Studies",
        teacher: "Subhasini Gill III",
      },
      {
        day: "Fri",
        number: 6,
        subject: "Ethics",
        teacher: "Sujata Varman MD",
      },
      {
        day: "Fri",
        number: 7,
        subject: "Psychology",
        teacher: "Sweta Achari Sr.",
      },
      {
        day: "Fri",
        number: 8,
        subject: "Computer Science",
        teacher: "Ashlesh Mishra",
      },
      {
        day: "Sat",
        number: 1,
        subject: "Computer Science",
        teacher: "Ekaksh Reddy",
      },
      {
        day: "Sat",
        number: 2,
        subject: "Economics",
        teacher: "Shankar Khan MD",
      },
      {
        day: "Sat",
        number: 3,
        subject: "Political Science",
        teacher: "Bhagavaan Mukhopadhyay",
      },
      {
        day: "Sat",
        number: 4,
        subject: "Psychology",
        teacher: "Chitramala Embranthiri-Chaturvedi",
      },
      {
        day: "Sat",
        number: 5,
        subject: "Political Science",
        teacher: "Mrs. Sunita Devar",
      },
      {
        day: "Sat",
        number: 6,
        subject: "Computer Science",
        teacher: "Mr. Uttam Kaniyar",
      },
      {
        day: "Sat",
        number: 7,
        subject: "Philosophy",
        teacher: "Vaidehi Arora",
      },
      {
        day: "Sat",
        number: 8,
        subject: "Chemistry",
        teacher: "Menaka Chopra",
      },
    ],
  },
];
